from enum import StrEnum

class ServerMessage(StrEnum):
    UNKNOWN_COMMAND = "UNKNOWN COMMAND"
    EMPTY_COMMAND = "EMPTY COMMAND"
    INVALID_COMMAND = "INVALID COMMAND"
    INVALID_OPERATION = "INVALID OPERATION"
    INVALID_ORDER_TYPE = "INVALID ORDER TYPE"
    INVALID_ORDER_TYPE_ARGUMENTS = "INVALID NUMBER ARGUMENTS FOR ORDER TYPE"
    ERROR_CREATE_ORDER = "ERROR CREATE ORDER"
    EMPTY_TICKER_ARGUMENT = "EMPTY TICKER ARGUMENT"
    INCORRECT_TICKER_NAME = "INCORRECT TICKER NAME"